language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
   packages:
    - g++-4.8
env:
  CXX=g++-4.8
